### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by hsluoyz** [paysuper/casbin-server#13]
https://github.com/paysuper/casbin-server#pasysuper-casbin-server

![image](https://user-images.githubusercontent.com/3787410/87239624-d2666400-c443-11ea-8879-3b4244852d26.png)

**Comment by hsluoyz** [comment]
@vtolstov

**Comment by vtolstov** [comment]
I dont have control on this repo, sorry

**Comment by hsluoyz** [comment]
@vesvalo

**Comment by vesvalo** [comment]
Fixed, thanks!
